btn_once_en_g.destroy()
    # btn_g_en_once.destroy()
    # btn_kg_en_livre.destroy()
    # btn_livre_en_kg.destroy()
    # btn_ml_en_tasse.destroy()
    # btn_tasse_en_ml.destroy()
    # btn_l_en_gallon.destroy()
    # btn_gallon_en_l.destroy()
    # btn_C_en_F.destroy()
    # btn_F_en_C.destroy()
    # btn_ha_en_m2.destroy()
    # btn_m2_en_ha.destroy()
    # btn_ms_en_kmh.destroy()
    # btn_kmh_en_ms.destroy()